### ISSUE TITLE
how to install it?

### ISSUE THREAD

**Issue by jeremy886** [yebrahim/python-difflib-gui#15]
I just downloaded the zip file and run:
```
python3 pydiff.py
 
Traceback (most recent call last):
  File "pydiff.py", line 25, in <module>
    from ui.mainwindow import *
  File "/Users/apple/workplace/pydiff/ui/mainwindow.py", line 26, in <module>
    from difflibparser.difflibparser import *
ImportError: No module named 'difflibparser.difflibparser'
```

Thanks.

**Comment by yelsayd** [comment]
I guess it's my bad I didn't make this clear. This repo uses a submodule, so the easiest way is to just clone it recursively. Run the following: `git clone --recursive https://github.com/yebrahim/pydiff.git` and you'll get the `difflibparser` module as well. I've updated the `README` to include this. Unfortunately, Github's zip download does not include submodules :(.

**Comment by jeremy886** [comment]
It works now by using "git clone --recursive https://github.com/yebrahim/pydiff.git" instead of download the zip file.

https://flic.kr/p/N9CQUP

I'm using it to grade student's code.

Thank you for your help!

**Comment by yelsayd** [comment]
Great! Please feel free to open issues for any bugs/features you have.
