### ISSUE TITLE
Make compatible with Python3

### ISSUE THREAD

**Issue by KyferEz** [yebrahim/python-difflib-gui#16]
Python 2 is nearing EOL. Can we make this compatible with Python 3? I was attempting to do so as much of it is just Tkinter import commands that have changed, however have hit on this error which has stalled my progress. 

EDIT: Perhaps it's this: https://stackoverflow.com/questions/41524531/python-2-vs-python-3-class-with-iter

```
TypeError: iter() returned non-iterator of type 'DifflibParser'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Programs\Python35-32\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "C:\Programs\cygwin\home\Travis\sjscripts\pydiff\ui\mainwindow.py", line 89, in __browse_files
    self.filesChanged()
  File "C:\Programs\cygwin\home\Travis\sjscripts\pydiff\ui\mainwindow.py", line 192, in filesChanged
    self.diff_files_into_text_areas()
  File "C:\Programs\cygwin\home\Travis\sjscripts\pydiff\ui\mainwindow.py", line 229, in diff_files_into_text_areas
    for line in diff:
TypeError: iter() returned non-iterator of type 'DifflibParser'
```

**Comment by KyferEz** [comment]
Here's the full list of changes to make it compatible with Python3:

mainwindow_ui.py, change the imports to this:
```
from tkinter import *
#from Tkinter.ttk import *
from tkinter.messagebox import showerror
from tkinter import font
from tkinter import ttk
from tkinter.ttk import Treeview
import os
from ui.searchtextdialog import *
```

searchtextdialog.py change the imports to this:
```
from tkinter import *
```

mainwindow.py change the imports to this:
```
import os
import mimetypes
import filecmp
from difflibparser.difflibparser import *
from ui.mainwindow_ui import MainWindowUI
from tkinter import *
from tkinter.filedialog import askopenfilename, askdirectory
from tkinter.simpledialog import askstring
```

difflibparser.py change line 45 from def next(self): to:
```
    def __next__(self):
```

**Comment by yelsayd** [comment]
Thanks for the interest @KyferEz, would you be up for sending a PR with these changes?

**Comment by KyferEz** [comment]
@yebrahim sure will give it a go

**Comment by KyferEz** [comment]
@yebrahim PRs completed for both pydiff and difflibparser

**Comment by TheSandDoctor** [comment]
I am still getting this exact error using the lastest repo version and python 3.8. @KyferEz it appears that your last suggestion with next(self) was not implemented.

**Comment by TheSandDoctor** [comment]
I have opened #19 to resolve this. Turns out that this repo is linking to an old commit version of difflibparser.
