### ISSUE TITLE
Make scrolling on x-axis also in sync

### ISSUE THREAD

**Issue by TheSandDoctor** [yebrahim/python-difflib-gui#21]
How would I change this behaviour so that the two windows scroll in sync on the x-axis as well?  Currently not having much luck. Thanks! @yebrahim

**Comment by yelsayd** [comment]
I haven't played around with this, but you'd probably need to create two scroll bars at the bottom, and bind each of them to scroll both. Kind of how the `scrollBoth` method is called [here](https://github.com/yebrahim/pydiff/blob/2c2a95e4dd4d1dbbe6cdacc18921f4d79f612d93/ui/mainwindow_ui.py#L206).
